# Generated by Django 4.0.1 on 2022-02-18 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('CondominioId', models.AutoField(primary_key=True, serialize=False)),
                ('Condominio', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=1000, null=True)),
                ('Localizacao', models.CharField(blank=True, max_length=1000, null=True)),
                ('NomeDoEdificio', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaImovel',
            fields=[
                ('FichaImovelId', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoUnico', models.CharField(blank=True, max_length=100, null=True)),
                ('DataCadastro', models.DateTimeField(auto_now_add=True)),
                ('CantoDePedra', models.BooleanField(default=True)),
                ('MotivoCantoDePedra', models.CharField(blank=True, max_length=300, null=True)),
                ('DataUltimaModificacao', models.DateTimeField(auto_now=True)),
                ('CondominioFk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha_imovel.condominio')),
                ('InstituicaoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicao.instituicao')),
            ],
        ),
    ]
