# Generated by Django 4.0.1 on 2022-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_imovel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaimovel',
            name='Academia',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='AceitaPermuta',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Aonde',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='AreaConstruida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='AreaGourmet',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='AreaTerreno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='AtualizacaoObs',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Banheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='CaptacaoFicha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Comissao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='CondicoesObs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='DataAtualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Dependencia',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Descricao',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='DocumentacaoNaEmpresa',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='ElevadorServico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='ElevadorSocial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='EntregaEm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='FotosCondominio',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='FotosImovel',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='HabiteSe',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='HidrometroIndvidual',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=0),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='IptuAtual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='MotivoDavenda',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='NumeroInscricao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='NumeroPavmento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='OnibusVan',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Opcionista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Piscina',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Placa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='PlayGround',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Posicao',
            field=models.IntegerField(choices=[(0, ''), (1, 'Fundos'), (2, 'Frente'), (3, 'Lateral')], default=0),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='QuadraSports',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='SalaoDeFestas',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Sauna',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='SituacaoImovel',
            field=models.IntegerField(blank=True, choices=[(0, 'Vazio'), (1, 'Ocupado')], null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Sol',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Subsolo',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Suites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='UnidadeAndar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Vagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='ValorCondominio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='ValorVenda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='balsa',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='outro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='qual',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='CantoDePedra',
            field=models.BooleanField(default=False),
        ),
    ]
