# Generated by Django 4.0.1 on 2022-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_imovel', '0003_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='Condominio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Condomínio'),
        ),
    ]
