# Generated by Django 4.0.1 on 2022-03-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_imovel', '0004_alter_condominio_condominio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaimovel',
            old_name='balsa',
            new_name='Balsa',
        ),
        migrations.AddField(
            model_name='fichaimovel',
            name='Agendar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='Endereco',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='Localizacao',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='NomeDoEdificio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nome do edifício'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='AceitaPermuta',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1, verbose_name='Aceita Permuta'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='AreaConstruida',
            field=models.FloatField(blank=True, null=True, verbose_name='Área construída'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='AreaGourmet',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Área Gourmet'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='AreaTerreno',
            field=models.FloatField(blank=True, null=True, verbose_name='Área do terreno'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='AtualizacaoObs',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Atualização Obs.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Banheiros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de Banheiros'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='CantoDePedra',
            field=models.BooleanField(default=False, verbose_name='Canto de Pedra'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='CaptacaoFicha',
            field=models.FloatField(blank=True, null=True, verbose_name='Captação Ficha'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='CodigoUnico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CÓDIGO UN.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Comissao',
            field=models.FloatField(blank=True, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='CondicoesObs',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Condições/Obs.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='DataAtualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='DataCadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do laudo'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Dependencia',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Dependência'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Descricao',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='DocumentacaoNaEmpresa',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Documentação na empresa'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='ElevadorServico',
            field=models.BooleanField(default=True, verbose_name='Elev Serv.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='ElevadorSocial',
            field=models.BooleanField(default=True, verbose_name='Elev Soc.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='EntregaEm',
            field=models.DateField(blank=True, null=True, verbose_name='E ntrega em'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='FotosCondominio',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Fotos cond.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='FotosImovel',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Fotos imóvel'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='HabiteSe',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Habite-se'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='HidrometroIndvidual',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=0, verbose_name='Hidrômetro individual'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='IptuAtual',
            field=models.FloatField(blank=True, null=True, verbose_name='IPTU Anual'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='MotivoCantoDePedra',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo Canto de Pedra'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='MotivoDavenda',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo da venda'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='NumeroInscricao',
            field=models.IntegerField(blank=True, null=True, verbose_name='No de Inscrição'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='NumeroPavmento',
            field=models.IntegerField(blank=True, null=True, verbose_name='No Pav'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='OnibusVan',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1, verbose_name='Ônibus/Van'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='PlayGround',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Play Ground'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Posicao',
            field=models.IntegerField(choices=[(0, ''), (1, 'Fundos'), (2, 'Frente'), (3, 'Lateral')], default=0, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='QuadraSports',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Quadra sports'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='SalaoDeFestas',
            field=models.IntegerField(blank=True, choices=[(0, 'Sim'), (1, 'Nao')], null=True, verbose_name='Salão de festas'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='SituacaoImovel',
            field=models.IntegerField(blank=True, choices=[(0, 'Vazio'), (1, 'Ocupado')], null=True, verbose_name='Imóvel'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='Suites',
            field=models.IntegerField(blank=True, null=True, verbose_name='Suítes'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='UnidadeAndar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unid./Andar'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='ValorCondominio',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Cond.'),
        ),
        migrations.AlterField(
            model_name='fichaimovel',
            name='ValorVenda',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Venda'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='Conjge',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cônjuge'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='ConjugeCel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cel'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='ConjugeE_mail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='E_mail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='TelCelular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='TelComercial',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Com.'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='TelResidencial',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Res.'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Proprietário'),
        ),
    ]
