# Generated by Django 4.0.1 on 2022-03-03 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instituicao', '0001_initial'),
        ('ficha_imovel', '0005_rename_balsa_fichaimovel_balsa_fichaimovel_agendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaimovel',
            name='Condominio',
        ),
        migrations.RemoveField(
            model_name='fichaimovel',
            name='DataCadastro',
        ),
        migrations.RemoveField(
            model_name='fichaimovel',
            name='Instituicao',
        ),
        migrations.RemoveField(
            model_name='fichaimovel',
            name='Proprietario',
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('instituicao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='instituicao.instituicao')),
                ('fichaimovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ficha_imovel.fichaimovel')),
                ('proprietario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ficha_imovel.proprietario')),
                ('condominio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ficha_imovel.condominio')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('LaudoId', models.AutoField(primary_key=True, serialize=False)),
                ('DataCadastroLaudo', models.DateTimeField(auto_now_add=True, verbose_name='Data do laudo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'abstract': False,
            },
            bases=('ficha_imovel.condominio', 'ficha_imovel.proprietario', 'ficha_imovel.fichaimovel', 'instituicao.instituicao', models.Model),
        ),
    ]
