# Generated by Django 4.0.1 on 2022-02-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('InstituicaoId', models.AutoField(primary_key=True, serialize=False)),
                ('NomeFantasia', models.CharField(blank=True, max_length=800, null=True)),
                ('RazaoSocial', models.CharField(blank=True, max_length=800, null=True)),
                ('Cnpj', models.CharField(blank=True, max_length=800, null=True)),
                ('TipoInstituicao', models.CharField(choices=[('admin', 'Administrador'), ('coretoraImovel', 'Corretora de Imóvel')], default='coretoraImovel', max_length=100)),
                ('Dominio', models.CharField(blank=True, max_length=1000, null=True)),
                ('DataCadastro', models.DateTimeField(auto_now_add=True)),
                ('Ativo', models.BooleanField(default=True)),
                ('ficha_instituicao', models.BooleanField(default=True)),
            ],
        ),
    ]
